### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by LeticiaAires** [LeticiaAires/Gravity-Glitch#2]
## Description

Develop an interactive interface that will work as the game's menu

## Tasks

- [x] Create the button play
- [x] Create the button rules
- [x] Create the button credits
- [x] Create the button quit
- [x] Create the button options

# Acceptance Criteria

- [x] Make all of the buttons functional
