### ISSUE TITLE
Pipe Height Generator

### ISSUE THREAD

**Issue by LeticiaAires** [LeticiaAires/Gravity-Glitch#3]
## Description

Development of an automatic pipe height generator, so as to possibilitate the bird's movement

## Tasks

- [ ] Establish height parameters
- [ ] Randomize it
- [ ] Create infinite loop

# Acceptance Criteria
- [ ] Succed in 30 seconds of the game, in order to test the established pipe height parameters
