### ISSUE TITLE
Bird

### ISSUE THREAD

**Issue by LeticiaAires** [LeticiaAires/Gravity-Glitch#4]
## Description

Creation of the main character of the game, "flappy"

## Tasks

- [ ] Create the bird colision to pipes
- [ ] Make it "fly"
- [ ] Create bird apperance

# Acceptance Criteria

- [ ] The bird doesn't go through pipes
- [ ] The bird can easily jump through the pipe wholes
- [ ] The bird has a sprite
