### ISSUE TITLE
Documentations

### ISSUE THREAD

**Issue by LeticiaAires** [LeticiaAires/Gravity-Glitch#5]
## Description

Development of all of the project's documentation, tutorial and templates

## Tasks

- [x] First VScode and Pygame steps tutorial
- [ ] Branch guide tutorial
- [x] Pushing and Pulling, how to upload your code into github tutorial
- [ ] Issue tutorial
- [x] Issue template 
- [ ] Commit template
- [ ] Gitpages documentation

# Acceptance Criteria
These are the necessary criteria used to consider that the issue was correctly executed
- [ ] The documentation is considered clear by other colleagues
- [ ] The documentation is considered clear by the teachers
- [ ] The documentation is descriptive and instructive
